const SERVER_ERROR = 500;
const INPUT_ERROR = 400;
const NOT_FOUND_ERROR = 404;
const AUTHORIZATION_ERROR = 401;
const CONFLICT_ERROR = 409;

module.exports = {
  SERVER_ERROR,
  INPUT_ERROR,
  NOT_FOUND_ERROR,
  AUTHORIZATION_ERROR,
  CONFLICT_ERROR,
};
